# Generated by Django 4.1.6 on 2023-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateline',
            field=models.DateField(),
        ),
    ]
