# Generated by Django 4.1.6 on 2023-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_featured_image_alter_post_dateline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
    ]
