# Generated by Django 4.1.6 on 2023-04-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_featured_image_post_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('image',)},
        ),
    ]
