# Generated by Django 4.1.6 on 2023-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
