# Generated by Django 4.1.6 on 2023-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_image_alter_post_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
