# Generated by Django 4.1.6 on 2023-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='home_content',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=50, null=True),
        ),
    ]
