# Generated by Django 4.1.6 on 2023-05-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_home_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
