# Generated by Django 4.1.6 on 2023-05-13 05:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
