# Generated by Django 4.1.6 on 2023-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(unique=True, upload_to='ads_images/'),
        ),
    ]
